/******************************************************************************
 *                       RNL CONTINUATION ALIGNMENT CHECK                     *
 ******************************************************************************
 *                                                                            *
 * Checks the alignment of continuation lines in the Pascal sources of RNL.   *
 *                                                                            *
 * RNL lines up the continuation of an unclosed parenthesis with the first    *
 * character after that parenthesis:                                          *
 *                                                                            *
 *     procedure WriteLongMessageHeader(const aData:TRNLPointer;              *
 *                                      const aMessageNumber:TRNLUInt16;      *
 *                                      const aOffset,aLength:TRNLUInt32);    *
 *                                                                            *
 *     result:=fPeer.fMTU-(RNL_IP_HEADER_SIZE+                                *
 *                         RNL_UDP_HEADER_SIZE+                               *
 *                         SizeOf(TRNLProtocolNormalPacketHeader));           *
 *                                                                            *
 * Getting this wrong by a single space is easy to do and hard to see in      *
 * review, which is why it is worth checking mechanically.                    *
 *                                                                            *
 * A baseline file records the deviations which already exist, so that only   *
 * newly introduced ones are reported. Without it the pre-existing ones would *
 * drown out everything new.                                                  *
 *                                                                            *
 * Plain C and nothing else on purpose: this is a tool inside a repository    *
 * which depends on nothing, and a checker that drags in an interpreter would *
 * be a dependency of its own.                                                *
 *                                                                            *
 * Build:                                                                     *
 *   cd src/tests && cc -O2 -o checkalignment checkalignment.c                *
 *                                                                            *
 * Usage:                                                                     *
 *   ./checkalignment                   check, report new deviations          *
 *   ./checkalignment --all             report every deviation, baseline too  *
 *   ./checkalignment --write-baseline  accept the current state as baseline  *
 *   ./checkalignment FILE...           check the given files instead         *
 *                                                                            *
 * Exit codes: 0 nothing new, 1 new deviations found, 2 usage or file error.  *
 *                                                                            *
 * A file named on the command line is reported under the name it was given.  *
 * The default run, which is the one the baseline is keyed on, is unaffected: *
 * there the names come from the list above either way.                       *
 *                                                                            *
 ******************************************************************************/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

/* Relative to the repository root, which is two levels up from this file */
static const char *const DEFAULT_PATHS[] = {
  "src/RNL.pas",
  "src/tests/RNLTestFramework.pas",
  "src/tests/RNLTestNetworkFaultInjector.pas",
  "src/tests/RNLTestHostPair.pas",
  "src/tests/RNLTestSTUNServer.pas",
  "src/tests/RNLTestDTLSServer.pas",
  "src/tests/RNLTestNATNetwork.pas",
  "src/tests/RNLTestTURNServer.pas",
  "src/tests/RNLTestNetworkBottleneck.pas",
  "src/tests/RNLTestRegressions.pas",
  /* Generated by the chain vector tool, and checked all the same: a rule which only applies to
     what was typed by hand is a rule with a hole in it, and the generator is the thing to fix
     when this complains. */
  "src/tests/RNLTestCertificates.pas",
  "src/tests/RNLTests.dpr",
  "examples/test1/test1.dpr",
  "examples/combinedexample/combinedexample.dpr",
};
#define DEFAULT_PATH_COUNT ((int)(sizeof(DEFAULT_PATHS)/sizeof(DEFAULT_PATHS[0])))

#define BASELINE_NAME "checkalignment.baseline"

/* Deep enough for anything Pascal nests in practice; a file which went past it would be
   reported rather than silently mis-scanned. */
#define MAXIMUM_DEPTH 256

typedef struct {
  int column;   /* column of the first character after the bracket */
  int hanging;  /* nothing but whitespace or a comment followed it on its own line */
} Bracket;

/* Tracks the columns of unclosed brackets across lines.

   Both parentheses and square brackets count, because a set or array constructor is aligned in
   exactly the same way as a parameter list, and the two nest freely:

       ConsoleOutput(Format('...',
                            [Event.Peer.LocalPeerID,
                             Event.Peer.RemotePeerID]));

   Pascal comments have to be recognised, and not only for tidiness: a compiler directive such
   as {$if defined(fpc)} is a brace comment which contains parentheses, so ignoring comments
   would corrupt the bracket stack outright. String literals have to be recognised for the same
   reason.

   "hanging" means nothing but whitespace or a comment followed the bracket on its own line,
   which is how Pascal writes enumerations and variant record parts:

       TRNLPeerState=
        (
         RNL_PEER_STATE_DISCONNECTED,

       0:(
          ui8:array[0..23] of TRNLUInt8;
         );

   Their contents are indented by one level rather than aligned to the bracket, so the alignment
   rule does not apply to them and they are exempt. */
typedef struct {
  Bracket stack[MAXIMUM_DEPTH];
  int depth;
  int overflowed;
  int in_brace;       /* { ... } */
  int in_paren_star;  /* (* ... *) */
} Scanner;

static void scanner_initialize(Scanner *aScanner) {
  aScanner->depth = 0;
  aScanner->overflowed = 0;
  aScanner->in_brace = 0;
  aScanner->in_paren_star = 0;
}

static void scanner_feed(Scanner *aScanner, const char *aLine, size_t aLength) {
  size_t index = 0;
  int in_string = 0;

  while (index < aLength) {
    char ch = aLine[index];

    if (aScanner->in_brace) {
      if (ch == '}') {
        aScanner->in_brace = 0;
      }
      index++;
      continue;
    }

    if (aScanner->in_paren_star) {
      if ((ch == '*') && ((index + 1) < aLength) && (aLine[index + 1] == ')')) {
        aScanner->in_paren_star = 0;
        index += 2;
        continue;
      }
      index++;
      continue;
    }

    if (in_string) {
      if (ch == '\'') {
        /* A doubled quote is an escaped quote and stays inside the string */
        if (((index + 1) < aLength) && (aLine[index + 1] == '\'')) {
          index += 2;
          continue;
        }
        in_string = 0;
      }
      index++;
      continue;
    }

    if (ch == '\'') {
      in_string = 1;
      index++;
      continue;
    }

    if (ch == '{') {
      aScanner->in_brace = 1;
      index++;
      continue;
    }

    if ((ch == '(') && ((index + 1) < aLength) && (aLine[index + 1] == '*')) {
      aScanner->in_paren_star = 1;
      index += 2;
      continue;
    }

    if ((ch == '/') && ((index + 1) < aLength) && (aLine[index + 1] == '/')) {
      break;
    }

    if ((ch == '(') || (ch == '[')) {
      size_t rest = index + 1;
      int hanging;
      while ((rest < aLength) && isspace((unsigned char)aLine[rest])) {
        rest++;
      }
      hanging = (rest >= aLength) ||
                ((aLine[rest] == '/') && ((rest + 1) < aLength) && (aLine[rest + 1] == '/'));
      if (aScanner->depth < MAXIMUM_DEPTH) {
        aScanner->stack[aScanner->depth].column = (int)(index + 1);
        aScanner->stack[aScanner->depth].hanging = hanging;
        aScanner->depth++;
      } else {
        aScanner->overflowed = 1;
      }
    } else if ((ch == ')') || (ch == ']')) {
      if (aScanner->depth > 0) {
        aScanner->depth--;
      }
    }

    index++;
  }
}

/* The indentation a continuation line has to have, or -1 when there is nothing open or the
   innermost open bracket is one of the exempt hanging ones. */
static int scanner_expected_indent(const Scanner *aScanner) {
  if (aScanner->depth <= 0) {
    return -1;
  }
  if (aScanner->stack[aScanner->depth - 1].hanging) {
    return -1;
  }
  return aScanner->stack[aScanner->depth - 1].column;
}

static int scanner_inside_comment(const Scanner *aScanner) {
  return aScanner->in_brace || aScanner->in_paren_star;
}

/* The length of the line without its trailing // comment, for deciding what it ends with */
static size_t code_length(const char *aLine, size_t aLength) {
  int quote = 0;
  size_t index;
  for (index = 0; index < aLength; index++) {
    if (aLine[index] == '\'') {
      quote ^= 1;
    } else if ((quote == 0) && (aLine[index] == '/') &&
               ((index + 1) < aLength) && (aLine[index + 1] == '/')) {
      return index;
    }
  }
  return aLength;
}

/* Whether the next line continues an item list rather than an expression.

   A parameter list, an argument list and a set constructor break after a separator, so the
   previous line ends with one of , ; ( or [. A continued expression breaks after an operator
   instead:

       inc(Carry,(aX.ui8[(Index shl 2) or 0] shl 0) or
                 (aX.ui8[(Index shl 2) or 1] shl 8) or

   Such a continuation is legitimately aligned under its own first operand rather than under the
   argument list, and there is no single correct column for it, so it is left alone. */
static int continues_a_list(const char *aCode, size_t aLength) {
  while ((aLength > 0) && isspace((unsigned char)aCode[aLength - 1])) {
    aLength--;
  }
  if (aLength == 0) {
    return 0;
  }
  switch (aCode[aLength - 1]) {
    case ',': case ';': case '(': case '[': return 1;
    default: return 0;
  }
}

typedef struct {
  char *path;
  int line_number;
  int expected;
  int actual;
  char *text;
} Deviation;

typedef struct {
  Deviation *items;
  int count;
  int capacity;
} Deviations;

static void deviations_add(Deviations *aList, const char *aPath, int aLineNumber,
                           int aExpected, int aActual, const char *aText) {
  if (aList->count >= aList->capacity) {
    int capacity = (aList->capacity > 0) ? (aList->capacity * 2) : 64;
    Deviation *items = (Deviation *)realloc(aList->items, (size_t)capacity * sizeof(Deviation));
    if (!items) {
      fprintf(stderr, "checkalignment: out of memory\n");
      exit(2);
    }
    aList->items = items;
    aList->capacity = capacity;
  }
  aList->items[aList->count].path = strdup(aPath);
  aList->items[aList->count].line_number = aLineNumber;
  aList->items[aList->count].expected = aExpected;
  aList->items[aList->count].actual = aActual;
  aList->items[aList->count].text = strdup(aText);
  aList->count++;
}

static char *read_whole_file(const char *aPath, size_t *aSize) {
  FILE *stream = fopen(aPath, "rb");
  char *data;
  long size;
  if (!stream) {
    return NULL;
  }
  if ((fseek(stream, 0, SEEK_END) != 0) || ((size = ftell(stream)) < 0)) {
    fclose(stream);
    return NULL;
  }
  rewind(stream);
  data = (char *)malloc((size_t)size + 1);
  if (!data) {
    fclose(stream);
    return NULL;
  }
  if (fread(data, 1, (size_t)size, stream) != (size_t)size) {
    free(data);
    fclose(stream);
    return NULL;
  }
  fclose(stream);
  data[size] = 0;
  *aSize = (size_t)size;
  return data;
}

/* Every deviation of one file. CR LF, LF and a lone CR all end a line, because the Pascal
   sources are CR LF and nothing else here may depend on that. */
static int check_file(const char *aAbsolutePath, const char *aRelativePath, Deviations *aList) {
  size_t size = 0;
  char *data = read_whole_file(aAbsolutePath, &size);
  size_t start = 0;
  int line_number = 0;
  Scanner scanner;
  char *previous_code = NULL;
  size_t previous_code_length = 0;

  if (!data) {
    return 0;
  }
  scanner_initialize(&scanner);

  while (start <= size) {
    size_t end = start;
    size_t next;
    size_t length;
    size_t lead, trail;
    int expected;

    while ((end < size) && (data[end] != '\n') && (data[end] != '\r')) {
      end++;
    }
    if (end >= size) {
      next = size + 1;
      if (start == size) {
        break; /* the trailing newline does not open another line */
      }
    } else if ((data[end] == '\r') && ((end + 1) < size) && (data[end + 1] == '\n')) {
      next = end + 2;
    } else {
      next = end + 1;
    }
    length = end - start;
    line_number++;

    lead = 0;
    while ((lead < length) && isspace((unsigned char)data[start + lead])) {
      lead++;
    }
    trail = length;
    while ((trail > lead) && isspace((unsigned char)data[start + trail - 1])) {
      trail--;
    }

    expected = scanner_expected_indent(&scanner);

    /* Only lines which really continue an item list are of interest. Empty lines and lines
       inside a block comment carry no alignment of their own, a line which only closes what was
       opened sits one level further left by convention, and a continued expression has no single
       correct column. */
    if ((expected >= 0) && (trail > lead) && !scanner_inside_comment(&scanner) &&
        (data[start + lead] != ')') && (data[start + lead] != ']') &&
        (previous_code && continues_a_list(previous_code, previous_code_length))) {
      if ((int)lead != expected) {
        char *text = (char *)malloc(trail - lead + 1);
        if (!text) {
          fprintf(stderr, "checkalignment: out of memory\n");
          exit(2);
        }
        memcpy(text, data + start + lead, trail - lead);
        text[trail - lead] = 0;
        deviations_add(aList, aRelativePath, line_number, expected, (int)lead, text);
        free(text);
      }
    }

    scanner_feed(&scanner, data + start, length);

    if ((trail > lead) &&
        !((data[start + lead] == '/') && ((lead + 1) < length) && (data[start + lead + 1] == '/'))) {
      size_t code = code_length(data + start, length);
      free(previous_code);
      previous_code = (char *)malloc(code + 1);
      if (!previous_code) {
        fprintf(stderr, "checkalignment: out of memory\n");
        exit(2);
      }
      memcpy(previous_code, data + start, code);
      previous_code[code] = 0;
      previous_code_length = code;
    }

    start = next;
  }

  free(previous_code);
  free(data);
  return 1;
}

/* Identifies a deviation by content rather than by line number, so that the baseline survives
   every insertion and deletion elsewhere in the same file. */
static void signature_of(char *aBuffer, size_t aBufferSize, const Deviation *aDeviation) {
  snprintf(aBuffer, aBufferSize, "%s\t%d\t%d\t%s",
           aDeviation->path, aDeviation->expected, aDeviation->actual, aDeviation->text);
}

typedef struct {
  char **items;
  int count;
  int capacity;
  int present;
} Baseline;

static int baseline_load(Baseline *aBaseline, const char *aPath) {
  size_t size = 0;
  char *data = read_whole_file(aPath, &size);
  size_t start = 0;

  aBaseline->items = NULL;
  aBaseline->count = 0;
  aBaseline->capacity = 0;
  aBaseline->present = 0;

  if (!data) {
    return 0;
  }
  aBaseline->present = 1;

  while (start < size) {
    size_t end = start;
    size_t length;
    while ((end < size) && (data[end] != '\n')) {
      end++;
    }
    length = end - start;
    while ((length > 0) && (data[start + length - 1] == '\r')) {
      length--;
    }
    if ((length > 0) && (data[start] != '#')) {
      if (aBaseline->count >= aBaseline->capacity) {
        int capacity = (aBaseline->capacity > 0) ? (aBaseline->capacity * 2) : 64;
        aBaseline->items = (char **)realloc(aBaseline->items, (size_t)capacity * sizeof(char *));
        if (!aBaseline->items) {
          fprintf(stderr, "checkalignment: out of memory\n");
          exit(2);
        }
        aBaseline->capacity = capacity;
      }
      aBaseline->items[aBaseline->count] = (char *)malloc(length + 1);
      memcpy(aBaseline->items[aBaseline->count], data + start, length);
      aBaseline->items[aBaseline->count][length] = 0;
      aBaseline->count++;
    }
    start = (end < size) ? (end + 1) : size;
  }

  free(data);
  return 1;
}

static int baseline_contains(const Baseline *aBaseline, const char *aSignature) {
  int index;
  for (index = 0; index < aBaseline->count; index++) {
    if (strcmp(aBaseline->items[index], aSignature) == 0) {
      return 1;
    }
  }
  return 0;
}

/* The repository root, two levels above the directory this executable sits in */
static void repository_root(char *aBuffer, size_t aBufferSize, const char *aArgumentZero) {
  const char *slash = strrchr(aArgumentZero, '/');
  if (slash) {
    size_t length = (size_t)(slash - aArgumentZero);
    if (length >= aBufferSize) {
      length = aBufferSize - 1;
    }
    memcpy(aBuffer, aArgumentZero, length);
    aBuffer[length] = 0;
  } else {
    snprintf(aBuffer, aBufferSize, ".");
  }
  strncat(aBuffer, "/../..", aBufferSize - strlen(aBuffer) - 1);
}

int main(int argc, char **argv) {
  char root[PATH_MAX];
  char baseline_path[PATH_MAX];
  const char *paths[256];
  int path_count = 0;
  int write_baseline = 0;
  int report_all = 0;
  int index;
  Deviations found;
  Baseline baseline;

  found.items = NULL;
  found.count = 0;
  found.capacity = 0;

  for (index = 1; index < argc; index++) {
    if (strcmp(argv[index], "--write-baseline") == 0) {
      write_baseline = 1;
    } else if (strcmp(argv[index], "--all") == 0) {
      report_all = 1;
    } else if (strncmp(argv[index], "--", 2) == 0) {
      fprintf(stderr, "checkalignment: unknown option: %s\n", argv[index]);
      return 2;
    } else if (path_count < (int)(sizeof(paths) / sizeof(paths[0]))) {
      paths[path_count++] = argv[index];
    }
  }

  repository_root(root, sizeof(root), argv[0]);
  snprintf(baseline_path, sizeof(baseline_path), "%s/src/tests/%s", root, BASELINE_NAME);

  if (path_count == 0) {
    for (index = 0; index < DEFAULT_PATH_COUNT; index++) {
      char absolute[PATH_MAX];
      snprintf(absolute, sizeof(absolute), "%s/%s", root, DEFAULT_PATHS[index]);
      if (!check_file(absolute, DEFAULT_PATHS[index], &found)) {
        fprintf(stderr, "checkalignment: no such file: %s\n", DEFAULT_PATHS[index]);
        return 2;
      }
    }
    path_count = DEFAULT_PATH_COUNT;
  } else {
    for (index = 0; index < path_count; index++) {
      if (!check_file(paths[index], paths[index], &found)) {
        fprintf(stderr, "checkalignment: no such file: %s\n", paths[index]);
        return 2;
      }
    }
  }

  if (write_baseline) {
    FILE *stream = fopen(baseline_path, "wb");
    if (!stream) {
      fprintf(stderr, "checkalignment: cannot write %s\n", baseline_path);
      return 2;
    }
    fputs("# Continuation line alignment deviations which already existed when\n", stream);
    fputs("# this baseline was taken. Only deviations which are not listed here\n", stream);
    fputs("# are reported, so that newly introduced ones stand out.\n", stream);
    fputs("#\n", stream);
    fputs("# Regenerate with: ./checkalignment --write-baseline\n", stream);
    fputs("# Identified by content, not by line number, so that the baseline\n", stream);
    fputs("# survives edits elsewhere in the same file.\n", stream);
    for (index = 0; index < found.count; index++) {
      char signature[4096];
      signature_of(signature, sizeof(signature), &found.items[index]);
      fprintf(stream, "%s\n", signature);
    }
    fclose(stream);
    printf("checkalignment: baseline written with %d entr%s\n",
           found.count, (found.count == 1) ? "y" : "ies");
    return 0;
  }

  if (write_baseline || report_all) {
    baseline.present = 0;
    baseline.count = 0;
    baseline.items = NULL;
    baseline.capacity = 0;
  } else {
    baseline_load(&baseline, baseline_path);
  }

  {
    int new_count = 0;
    for (index = 0; index < found.count; index++) {
      char signature[4096];
      signature_of(signature, sizeof(signature), &found.items[index]);
      if (baseline.present && baseline_contains(&baseline, signature)) {
        continue;
      }
      printf("%s:%d: continuation indented %d, expected %d | %s\n",
             found.items[index].path, found.items[index].line_number,
             found.items[index].actual, found.items[index].expected,
             found.items[index].text);
      new_count++;
    }

    if (new_count > 0) {
      printf("\n");
      printf("checkalignment: %d misaligned continuation line%s\n",
             new_count, (new_count == 1) ? "" : "s");
      if (!baseline.present) {
        printf("checkalignment: no baseline in effect, so this includes pre-existing ones\n");
      }
      return 1;
    }

    if (!baseline.present) {
      printf("checkalignment: %d file(s) checked, no deviations at all\n", path_count);
    } else {
      printf("checkalignment: %d file(s) checked, %d known deviation(s), nothing new\n",
             path_count, found.count);
    }
  }

  return 0;
}
